products/urls.py
from django.urls import path, include

from products import views


app_name = "products"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('my_products/', views.my_products, name='my_products'),
    path('delete/<int:id>/', views.delete_product, name="delete_product"),
    path('edit/<int:id>/', views.edit_product, name="edit_product"),

    

]

shopping_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace='users')),
    path('', include("web.urls", namespace='web')),
    path('products/', include("products.urls", namespace='products')),
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)


    )

web/urls.py
from django.urls import path, include
from web import views

app_name = "web"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.product, name='product'),
]

products/models.py
from django.db import models

# Create your models here.


class Brand(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    categories = models.ManyToManyField("products.Category")
    image = models.ImageField(upload_to="products/")
    price = models.DecimalField(max_digits=8, decimal_places=2)

    brand = models.ForeignKey("products.Brand", on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

products/forms.py
from django import forms

from products.models import Product


class ProductForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'input'}), label="Category")

    class Meta:
        model = Product
        exclude = ("brand", "is_deleted", "categories")

        widgets = {
            "title": forms.TextInput(attrs={'class': 'input'}),
            "short_descriptions": forms.Textarea(attrs={'class': 'input'}),
        }

products/views.py
import json

from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from products.forms import ProductForm
from products.models import Brand, Category, Product
from products.functions import generate_form_errors
# Create your views here.


@login_required(login_url="/users/login/")
def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            tags = form.cleaned_data['tags']
            if not Brand.objects.filter(user=request.user).exists():
                brand = Brand.objects.create(
                    user=request.user, name=request.user.username)
            else:
                brand = request.user.brand
            instance = form.save(commit=False)
            instance.brand = brand
            instance.save()

            tags_list = tags.split(",")
            for tag in tags_list:
                category, created = Category.objects.get_or_create(
                    title=tag.strip())
                instance.categories.add(category)

            response_data = {
                "title": "Successfully submitted",
                "message": "Successfully submitted",
                "status": "success",
                "redirect": "yes",
                "redirect_url": "/"
            }
        else:
            error_message = generate_form_errors(form)
            response_data = {
                "title": "form validation error",
                "message": str(error_message),
                "status": "error",
                "stable": "yes",
            }
        return HttpResponse(json.dumps(response_data), content_type='application/json')
    else:
        form = ProductForm()
        context = {
            "form": form,
            "title": "Add a new Product"

        }
        return render(request, "products/create.html", context=context)


@login_required(login_url="/users/login/")
def my_products(request):
    instances = Product.objects.filter(brand__user=request.user, is_deleted=False)

    context = {
        "title": "My Products",
        "instances": instances
    }
    return render(request, "products/my_products.html", context=context)

@login_required(login_url="/users/login/")
def delete_product(request, id):
    instance = get_object_or_404(Product, id=id)
    instance.is_deleted = True
    instance.delete()

    response_data = {
        "title": "successfully deleted",
        "message": "post deleted successfully",
        "status": "success"
    }

    return HttpResponse(json.dumps(response_data), content_type="application/json")


@login_required(login_url="/users/login/")
def edit_product(request, id):
    instance = get_object_or_404(Product, id=id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            tags = form.cleaned_data['tags']
            instance = form.save(commit=False)

            instance.save()
            instance.categories.clear()

            tags_list = tags.split(",")
            for tag in tags_list:
                category, created = Category.objects.get_or_create(
                    title=tag.strip())
                instance.categories.add(category)

            response_data = {
                "title": "Successfully submitted",
                "message": "Successfully submitted",
                "status": "success",
                "redirect": "yes",
                "redirect_url": "/"
            }
        else:
            error_message = generate_form_errors(form)
            response_data = {
                "title": "form validation error",
                "message": str(error_message),
                "status": "error",
                "stable": "yes",
            }
        return HttpResponse(json.dumps(response_data), content_type='application/json')

    else:
        category_string = ""
        for category in instance.categories.all():
            category_string += f"{category.title},"
        form = ProductForm(instance=instance, initial={
                        "tags": category_string[:-1]})
        context = {
            "title": "Create a new Product",
            'form': form,
        }
        return render(request, "products/create.html", context=context)

templates/products/create.html
{% extends "base.html" %} {% load static %} {% block content %}
<section id="edit-post-home">
  <section class="wrapper">
    {% include 'includes/header.html' %}
    <section class="spotlight">
      <h3>Create new Product</h3>
      <form
        action=""
        method="post"
        enctype="multipart/form-data"
        class="ajax redirect"
      >
        {% csrf_token %}
        <div class="form-field">
          <label for="{form.title.id_for_label"> {{form.title.label}} </label>
          {{form.title}}
        </div>
        <div class="form-field">
          <label for="{{form.description.label.id_for_label}}" class="subheads">
            {{form.description.label}}
          </label>
          <div class="description">{{form.description}}</div>
        </div>
        <div class="form-field">
          <label class="subheads" for="{{form.categories.label.id_for_label}}">
            {{form.tags.label}}
          </label>
          {{form.tags}}
        </div>
        <div class="form-field">
          <label for="{{form.price.label.id_for_label}}" class="subheads">
            {{form.price.label}}
          </label>
          <div class="price">{{form.price}}</div>
        </div>
        <div class="form-field">
          <label for="{{form.image.label.id_for_label}}" class="subheads">
            {{form.image.label}}
          </label>
          {{form.image}}
        </div>
        <div class="form-field">
          <input type="submit" value="Submit" />
        </div>
      </form>
      {{form.media}}
    </section>
  </section>
</section>
{% endblock %}

templates/products/my_products.html
{% extends "base.html" %} {% load static %} {% block content %}

<section id="my-posts-home">
  <section class="wrapper">
    {% include 'includes/header.html' %}
    <section class="spotlight">
      <h3 class="fw-bold">{{title}}</h3>
      <ul class="posts">
        {% for instance in instances %}
        <li class="post">
          <div class="top">
            <h5 class="title">{{instance.title}}</h5>
            <div class="buttons">
              <a
                href="{% url 'products:delete_product' id=instance.id %}"
                class="danger action-button reload"
                data-text="Are you sure want to remove this post. You can't undo this action."
                data-title="Confirm Delete!"
                title="Delete!"
              >
                <img
                  src="{% static 'images/icons/delete.svg' %}"
                  alt="Delete"
                />
              </a>
              <a
                href="{% url 'products:edit_product' id=instance.id %}"
                class="warning"
              >
                <img src="{% static 'images/icons/pencil.svg' %}" alt="Edit" />
              </a>
            </div>
          </div>
          <p class="description">{{instance.description}}</p>
          <div class="bottom">
            <a
              href="{% url 'web:product' id=instance.id %}"
              class="btn btn-dark"
            >
              View
            </a>
          </div>
        </li>
        {% endfor %}
      </ul>
    </section>
  </section>
</section>
{% endblock %}