products/urls.py
from django.urls import path, include

from products import views


app_name = "products"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('my_products/', views.my_products, name='my_products'),
    path('delete/<int:id>/', views.delete_product, name="delete_product"),
    path('edit/<int:id>/', views.edit_product, name="edit_product"),

    

]

shopping_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace='users')),
    path('', include("web.urls", namespace='web')),
    path('products/', include("products.urls", namespace='products')),
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)


    )

users/urls.py
from django.urls import path, include

from users import views


app_name = "users"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path("signup/",views.signup,name="signup"),
]

web/urls.py
from django.urls import path, include
from web import views

app_name = "web"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.product, name='product'),
]

templates/includes/header.html
{% load static %}
<header>
    <h1>
        <a href="{% url 'web:index' %}">
            <img
                src="{% static 'images/icons/logo.webp' %}"
                alt="Logo"
                style="width:75% ;"
            />
        </a>
    </h1>
    <div>
        {% if request.user.is_authenticated %}
        <a href="{% url 'products:create' %}" class="btn btn-dark">Create</a> 
        <a href="{% url 'products:my_products' %}" class="btn btn-dark">My Products</a>
        <a href="{%url 'users:logout' %}" class="btn btn-danger"> Logout </a>
        {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-success"> Login </a>
        <a href="{% url 'users:signup' %}"><button type="button" class="btn btn-success">signup</button></a>
        {% endif %} 
        <div>{{ request.user.username }}</div>

    <div>
    <div id="hamburger-icon">
        <img
            src="{% static 'images/icons/hamburger.svg' %}"
            alt="Hamburger"
        />
    </div>
</header>